---
# file: roles/fubarhouse.npm/tasks/iojs.yml

- name: "IOJS | Check"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  raw:  ". {{ nvm_lib_location }}/nvm.sh && nvm version"
  register: io_install_result
  ignore_errors: yes
  no_log: yes

- name: IOJS | Install
  become: yes
  become_user: root
  raw:  ". {{ nvm_lib_location }}/nvm.sh && nvm install iojs-v{{ default_io_version }}"
  when: "'{{ default_io_version }}' not in io_install_result.stdout"
