---
# file: roles/fubarhouse.npm/tasks/iojs.yml

- name: "IOJS | Check"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  raw: . {{ nvm_usr_location }}/nvm.sh && nvm ls
  register: io_install_result
  ignore_errors: True
  no_log: True

- name: IOJS | Install
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  raw: . {{ nvm_usr_location }}/nvm.sh && nvm install iojs-v{{ default_io_version }}
  when: "'{{ default_io_version }}' not in io_install_result.stdout"
