---
# file: roles/compass/tasks/nodejs.yml

- name: "NodeJS | Check"
  shell: sudo -iu {{ vagrant_user }} nvm ls | grep {{ default_node_version }}
  register: node_install_result
  ignore_errors: True
  no_log: True

- name: "NodeJS | Prepare"
  sudo: yes
  sudo_user: "{{ vagrant_user }}"
  lineinfile: >
    dest=~/.profile
    line="source /usr/local/.nvm/nvm.sh"
  when: "'{{ default_node_version }}' not in node_install_result.stdout"

- name: "NodeJS | Install"
  shell: sudo -iu {{ vagrant_user }} nvm install {{ default_node_version }}
  when: "'{{ default_node_version }}' not in node_install_result.stdout"

- name: "NodeJS | Linking"
  shell: sudo -iu {{ vagrant_user }} nvm alias default {{ default_node_version }}
  when: "'{{ default_node_version }}' not in node_install_result.stdout"

- name: "NodeJS | Configure"
  shell: export PATH=~/node_modules/.bin:$PATH
  when: "'{{ default_node_version }}' not in node_install_result.stdout"