---
# file: roles/fubarhouse.npm/tasks/nodejs.yml

- name: "NodeJS | Install"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell:  "{{ fubarhouse_npm.nvm_symlink_exec }} install {{ item }}"
  with_items: "{{ node_versions }}"

- name: "NodeJS | Switching"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell:  "{{ fubarhouse_npm.nvm_symlink_exec }} use {{ node_version }}"

- name: "NodeJS | Linking"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell:  "{{ fubarhouse_npm.nvm_symlink_exec }} alias default {{ node_version }}"

- name: "NodeJS | Import exports"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  lineinfile:
    dest: "{{ fubarhouse_npm.user_dir }}/{{ item.filename }}"
    line: "export PATH=$PATH:$(npm config --global get prefix)/bin"
    state: present
  with_items: "{{ fubarhouse_npm.shell_profiles }}"
