---
# file: roles/fubarhouse.npm/tasks/nodejs.yml

- name: "NodeJS | Check"
  raw: . {{ nvm_usr_location }}/nvm.sh && nvm ls | grep {{ default_node_version }}
  register: node_install_result
  ignore_errors: yes
  no_log: yes

- name: "NodeJS | Get installed versions"
  raw: . {{ nvm_usr_location }}/nvm.sh && nvm ls
  register: node_versions
  ignore_errors: yes
  no_log: yes

- name: "NodeJS | Install"
  raw: . {{ nvm_usr_location }}/nvm.sh && nvm install v{{ default_node_version }}
  when: "'{{ default_node_version }}' not in node_versions.stdout"

- name: "NodeJS | Linking"
  raw: . {{ nvm_usr_location }}/nvm.sh && nvm alias default v{{ default_node_version }}
  when: "'{{ default_node_version }}' not in node_install_result.stdout"
