---
# file: roles/fubarhouse.npm/tasks/nodejs.yml

- name: "NodeJS | Check"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  raw:  ". {{ nvm_lib_location }}/nvm.sh && nvm version | grep {{ default_node_version }}"
  register: node_install_result
  ignore_errors: yes
  no_log: yes

- name: "NodeJS | Install"
  become: yes
  become_user: root
  raw:  ". {{ nvm_lib_location }}/nvm.sh && nvm install v{{ default_node_version }}"
  when: "'{{ default_node_version }}' not in node_install_result.stdout"

- name: "NodeJS | Linking"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  raw:  ". {{ nvm_lib_location }}/nvm.sh && nvm alias default v{{ default_node_version }}"
  when: "'{{ default_node_version }}' not in node_install_result.stdout"
