---
# file: roles/fubarhouse.npm/tasks/npm.yml

- name: "NPM | Ensure installed and updated"
  become: yes
  become_user: root
  raw: bash  -c ". {{ nvm_usr_location }}/nvm.sh && npm install -g {{ item.name }}"
  with_items:
  - "{{ npm_packages }}"
