---
# file: roles/fubarhouse.npm/tasks/npm.yml

- name: "NPM | Ensure installed and updated"
  become: yes
  become_user: "root"
  npm:
    name: "{{ item.name }}"
    global: yes
    executable: /usr/local/bin/npm
    state: latest
  with_items:
  - "{{ npm_packages }}"
