---
# file: roles/fubarhouse.npm/tasks/npm.yml

- name: "NPM | Configure"
  shell: "{{ fubarhouse_npm.npm_install_exec }} config set prefix /usr/local"

- name: "NPM | Ensure installed and updated"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  npm:
    name: "{{ item.name }}"
    executable: "{{ fubarhouse_npm.npm_install_exec }}"
    path: "/home/{{ ansible_ssh_user }}/.npm/"
    state: latest
    global: no
  with_items:
    - "{{ fubarhouse_npm.packages }}"
