---
# file: roles/fubarhouse.npm/tasks/npm.yml

- name: "NPM | Ensure installed and updated"
  raw: . {{ nvm_usr_location }}/nvm.sh && npm install {{ item.name }}
  with_items:
  - "{{ npm_packages }}"
