---
# file: roles/fubarhouse.npm/tasks/nvm.yml

- name: "NVM | Check"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  stat: path={{ nvm_lib_location }}/nvm.sh
  register: nvm_installed

- name: "NVM | Install dependencies"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  apt: name={{ item }} state=installed
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev
  when: nvm_installed.stat.exists == false

- name: "NVM | Prepare"
  become: yes
  become_user: root
  file: path={{ nvm_lib_location }}/
        state=directory
        mode=0777
        recurse=yes

- name: "NVM | Clone"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  git: repo=https://github.com/creationix/nvm.git
       dest={{ nvm_lib_location }}
       clone=yes
       update=yes
       force=yes
       version=master
  when: nvm_installed.stat.exists == false

- name: "NVM | Install"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  command: "{{ nvm_lib_location }}/install.sh"
  when: nvm_installed.stat.exists == false
