---
# file: roles/fubarhouse.npm/tasks/nvm.yml

- name: "NVM | Clean-up"
  become: yes
  become_user: "root"
  file:
    path: "{{ fubarhouse_npm.nvm_install_dir }}"
    state: absent
  when: fubarhouse_npm.clean_install

- name: "NVM | Check"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  stat:
    path: "{{ fubarhouse_npm.nvm_install_dir }}"
  register: fubarhouse_npm_nvm_installed

- name: "NVM | Install dependencies"
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev
  when: fubarhouse_npm_nvm_installed.stat.exists == false

- name: "NVM | Ensure permissions are set"
  become: yes
  become_user: "root"
  file:
    path: "{{ fubarhouse_npm.nvm_install_dir }}"
    state: directory
    mode: 0777
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    recurse: yes

- name: "NVM | Clone/Update"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  git:
    repo: "{{ fubarhouse_npm.nvm_repo }}"
    dest: "{{ fubarhouse_npm.nvm_install_dir }}"
    clone: yes
    update: yes
    force: yes
    version: master
    recursive: false

- name: "NVM | Install"
  become: yes
  become_user: "root"
  shell: "{{ fubarhouse_npm.nvm_install_dir }}/install.sh"
  when: fubarhouse_npm_nvm_installed.stat.exists == false

- name: "NVM | Create an executable"
  become: yes
  become_user: "root"
  template:
    src: "nvm.sh"
    dest: "/usr/bin/nvm"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  when: fubarhouse_npm_nvm_installed.stat.exists == false

- name: NVM | Ensure shell profiles are available
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  file:
    path: /home/{{ ansible_ssh_user }}/{{ item.filename }}
    state: touch
  with_items: "{{ fubarhouse_python.shell_profiles }}"

- name: NVM | Ensure shell profiles are configured
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  lineinfile:
    dest: "/home/{{ ansible_ssh_user }}/{{ item.filename }}"
    state: present
    regexp: '^export PATH=$PATH:$(npm config --global get prefix)/bin;'
    line: 'export PATH=$PATH:$(npm config --global get prefix)/bin;'
  with_items: "{{ fubarhouse_python.shell_profiles }}"

