---
# file: roles/fubarhouse.npm/tasks/nvm.yml

- name: "NVM | Check"
  stat: path=/usr/local/.nvm/nvm.sh
  register: nvm_installed

- name: "NVM | Install dependencies"
  apt: name={{ item }} state=present
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev
  when: nvm_installed.stat.exists == false

- name: "NVM | Prepare"
  file: path=/usr/local/.nvm state=directory mode=0777 recurse=yes
  when: nvm_installed.stat.exists == false

- name: "NVM | Install"
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{ default_nvm_version }}/install.sh | NVM_DIR=/usr/local/.nvm bash
  when: nvm_installed.stat.exists == false
