---
# file: roles/fubarhouse.npm/tasks/nvm.yml

- name: "NVM | Clean-up"
  become: yes
  become_user: "root"
  file:
    path: "{{ fubarhouse_npm.nvm_install_dir }}"
    state: absent
  when: fubarhouse_npm.clean_install

- name: "NVM | Check"
  stat:
    path: "{{ fubarhouse_npm.nvm_install_dir }}"
  register: fubarhouse_npm_nvm_installed

- name: "NVM | Ensure permissions are set"
  become: yes
  become_user: "root"
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0777
    owner: "{{ fubarhouse_user }}"
    recurse: yes
  with_items: "{{ fubarhouse_npm.folder_paths }}"

- name: "NVM | Clone/Update"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  git:
    repo: "{{ fubarhouse_npm.nvm_repo }}"
    dest: "{{ fubarhouse_npm.nvm_install_dir }}"
    clone: yes
    update: yes
    force: yes
    version: master
    recursive: false

- name: "NVM | Install"
  become: yes
  become_user: "root"
  shell: "{{ fubarhouse_npm.nvm_install_dir }}/install.sh"
  when: fubarhouse_npm_nvm_installed.stat.exists == false

- name: "NVM | Create an executable"
  template:
    src: "nvm.sh"
    dest: "{{ fubarhouse_npm.nvm_symlink_exec }}"
    owner: "{{ fubarhouse_user }}"
    mode: 0755
  when: fubarhouse_npm_nvm_installed.stat.exists == false

- name: NVM | Ensure shell profiles are available
  become: yes
  become_user: "root"
  file:
    path: "{{ fubarhouse_npm.user_dir }}/{{ item.filename }}"
    state: touch
  with_items: "{{ fubarhouse_npm.shell_profiles }}"
  ignore_errors: yes

- name: NVM | Ensure shell profiles are configured for default version
  become: yes
  become_user: "root"
  lineinfile:
    dest: "{{ fubarhouse_npm.user_dir }}/{{ item.filename }}"
    regexp: '.nvm/v{{ node_version }}/bin'
    line:  'export PATH=$PATH:{{ fubarhouse_npm.user_dir }}/.nvm/v{{ node_version }}/bin;'
    state: present
  with_items:
    - "{{ fubarhouse_npm.shell_profiles }}"
  ignore_errors: yes

- name: NVM | Ensure shell profiles are configured for other versions
  become: yes
  become_user: "root"
  lineinfile:
    dest: "{{ fubarhouse_npm.user_dir }}/{{ item[0].filename }}"
    regexp: '.nvm/v{{ item[1] }}/bin'
    line:  'export PATH=$PATH:{{ fubarhouse_npm.user_dir }}/.nvm/v{{ item[1] }}/bin;'
    state: present
  with_nested:
    - "{{ fubarhouse_npm.shell_profiles }}"
    - "{{ node_versions }}"
  ignore_errors: yes